---
title: "Python Courses Index"
author: ""
date: ""
output: html_document
---

All projects presented here are from [Rice University online courses](https://www.coursera.org/specialization/fundamentalscomputing2/37).

#### An Introduction to Interactive Programming in Python (Part 1)
- Mini-Project 1: [Rock-paper-scissors-lizard-Spock](http://linzifan.github.io/python_courses/IPP-Project1)
- Mini-Project 2: ["Guess the number" game](http://linzifan.github.io/python_courses/IPP-Project2)
- Mini-Project 3: [Stopwatch: The Game](http://linzifan.github.io/python_courses/IPP-Project3)
- Mini-Project 4: ["Pong"](http://linzifan.github.io/python_courses/IPP-Project4)

#### An Introduction to Interactive Programming in Python (Part 2)
- Mini-Project 5: [Memory](http://linzifan.github.io/python_courses/IPP-Project5)
- Mini-Project 6: [Blackjack](http://linzifan.github.io/python_courses/IPP-Project6)
- Mini-Project 7: [Spaceship](http://linzifan.github.io/python_courses/IPP-Project7)



#### Principles of Computing (Part 1)
- Mini-Project 1: [2048 (Merge)](http://linzifan.github.io/python_courses/PoC-Project1)
- Mini-Project 2: [2048 (Full)](http://linzifan.github.io/python_courses/PoC-Project2)
- Mini-Project 3: [Tic-Tac-Toe (Monte Carlo)](http://linzifan.github.io/python_courses/PoC-Project3)
- Mini-Project 4: [Yahtzee](http://linzifan.github.io/python_courses/PoC-Project4)
- Mini-Project 5: [Cookie Clicker](http://linzifan.github.io/python_courses/PoC-Project5)
- Practice 1: [Solitaire Mancala](http://linzifan.github.io/python_courses/PoC-Practice1)
- Practice 2: [Nim (Monte Carlo)](http://linzifan.github.io/python_courses/PoC-Practice2)
- Practice 3: [The Case of the Greedy Boss](http://linzifan.github.io/python_courses/PoC-Practice3)


#### Principles of Computing (Part 2)
- Mini-Project 6: [Zombie Apocalypse (BFS)](http://linzifan.github.io/python_courses/PoC-Project6)
- Mini-Project 7: [Word Wrangler](http://linzifan.github.io/python_courses/PoC-Project7)
- Mini-Project 8: [Tic-Tac-Toe (Minimax)](http://linzifan.github.io/python_courses/PoC-Project8)

[Index](http://linzifan.github.io/python_courses/Index)
